### ISSUE TITLE
Going forward

### ISSUE THREAD

**Issue by aghamidi** [aghamidi/Brief-lecture-summaries#205]
Brother/Sister,

Would you be interested in proofreading assignments as a next step? We have now produced plenty of summaries, descriptions and other texts that need to be proofread to:
- fix typos and grammatical errors,
- ensure that the texts are within character limit target (500-550 including spaces),
- ensure that the summary describes what the topic of the lecture is and why it is important (in the case of the summaries), and
- ensure that the Arabic words and names are transliterated consistently and according to our template.

You will in shaa Allah be provided more information if you are interested. Otherwise, we can assign you similar tasks as before.

**Comment by kha-1islm** [comment]
As-salaamu alaikum.

Sorry for the delay in sending the write-ups.

I've three more issues—nos. 91 (Surah Maryam), 97 (surah al-Falaq) and 96 (Surah Kaafirun). I'll do these as fast as I can, InshaAllah.

Yes, I will like to proofread, InshaAllah.

**Comment by aghamidi** [comment]
wa alaykum al Salaam wa rahmatAllah wa barakatuhu. No problem. 

That's great. I will add some instructions to the proofreading here below in a day in shaa Allah, and after you finish those lectures, I will assign you texts to proofread, possibly in larger bulks. Barak Allah feekum

**Comment by aghamidi** [comment]
Btw, you don't need to write any more answers/summaries. Another brother will. Please stay tuned for the instructions on proofreading.

**Comment by aghamidi** [comment]
Below are the instructions on proofreading. Please copy and save them as well as the attached spreadsheet on your computer because it would be quite messy for me to add them to each issue.

Proofreading instructions:
Please correct all typos, grammatical errors and awkward phrasings that you notice.

Please make sure that the lecture summaries provides a) an overview of the content of the lecture (series) and b) a description of why the specific topic is important for Muslims to study. (In the case of other texts aside from lecture summaries, you can disregard this point.)

Please make sure that the summary consists of between 500-550 characters in total including spaces.

Please make sure that ALL Arabic words are transliterated according to the scheme in the attached file. (The first sheet describes the transliteration of individual letters while the second sheet contains a list of words that we've already transliterated which you can reference). The first letter of all Arabic words should be capitalised, i.e. ʾĪmān instead of ʾīmān. The word "Allah" and the names of our four lecturers (Anwar Al-Awlaki, Ahmad Musa Jibril, Ali Al-Tamimi and Mustapha Al-Majzoub) are the only words that should not be adjusted. Please make sure all other words are transliterated in a consistent way going forward by referring to the spreadsheet.

I know that the transliteration is annoying at first but after a while it should come naturally and will help us maintain a consistent language in shaa Allah. Also, in some cases, the written material that you've been provided is not sufficient. In those rare cases, could you please try to listen quickly to bits of the lecture to supplement the other material?

Barak Allah feekum for your patience.

**Comment by kha-1islm** [comment]
As salaamu alaikum wa rahamatullahi wa barakatuhu.

Yes, I have copied the instructions for proofreading; however, the file 'Dictionary.xlsx' does not open!
I get a security warning asking me whether I want to open the file but then when I click on 'open', it doesn't open.
Can you suggest what I should do?

JazakAllah Khair

**Comment by aghamidi** [comment]
wa alaykum alSalaam wa rahmatAllah wa barakatuhu.

Wa iyyakum. Can you try this link: http://yourfilestore.com/download/199237/Dictionary.xlsx.html

Btw, please make sure that you read the instructions on github and not the ones that were sent to your email because I edited the instructions after I posted them.

**Comment by kha-1islm** [comment]
As-salaamu alaikum.

Having the same problem again when opening the file. After the security warning, 'what do you want to do with this file' option appears again. It goes on like a cycle!

And yes, I will use the instructions on github for reference.

**Comment by aghamidi** [comment]
wa alaykum alSalaam wa rahmatAllah wa barakatuhu.

How about if you copy/paste the content in these documents:
Letters: https://ethercalc.org/c59oixuecd3b
Words: https://ethercalc.org/dyra8vugoze1

**Comment by kadoooo** [comment]
As-Salaamu Alaikum.

I want to help you in any way that I can please let me know if there is ANY thing that I can do to help.

**Comment by kha-1islm** [comment]
As-salaamu alaikum wa rahamatullahi wa barakatuhu.

Yes, I have copy-pasted the file contents.

**Comment by aghamidi** [comment]
wa alaykum alSalaam wa rahmatAllah wa barakatuhu. Alright. Then I will begin assigning you texts to proofread in shaa Allah
