### ISSUE TITLE
Future

### ISSUE THREAD

**Issue by aghamidi** [aghamidi/Brief-lecture-summaries#230]
بِسْمِ اللهِ الرَّحْمٰنِ الرَّحِيْمِ

Brothers/sisters,
we removed you from the lectures that you we assigned previously because you have been inactive for a period. If you are still interested in helping out, please let us know here.

@AbuSallahdin, @earthisabed, @mahbub227, @Asyia, @umarrr, @deeos, @kblavvv, @Aaminah82, @abuzgezgoz and @Ummsalamah

**Comment by deeos** [comment]
Still interested

**Comment by iqy007** [comment]
As salaam alaikum,
I was away for a while, still dealing with some family duties, will contact
you once I am available

**Comment by aghamidi** [comment]
Wa alaykum alSalaam wa rahmat Allah wa barakatuhu @iqy007 
Okay.

**Comment by abuzgezgoz** [comment]
Assalam alaikum warahmatullahh wabarakatuh, i did summary (Notes) on Hijra by Imam Anwar Awlaki, was that what you are looking for? i was waiting for your feedback before i go ahead with other tasks assigned. please note i am amateur in this field,..... I will need your guidance by pointing out on what i should be enhancing.....

**Comment by aghamidi** [comment]
wa alaykum alSalaam wa rahmatAllah wa barakatuhu
@abuzgezgoz 
I gave you feedback 17 days ago. You didn't reply so some other brother corrected it for you. These were the comments that I wrote on it: "Brother, please separate your text into separate answers to the above questions and make sure that you are answering the questions asked. The first question is about explaining what the content of the lecture is, not what Hijrah means. The second question is why the topic is important, not why Hijrah is obligatory."

Also, please do not unassign people from this conversation.

If you want to carry on writing summaries, accept the invitation below and I will in shaa Allah assign you new lectures. But you will have to be more active.
https://github.com/aghamidi/Detailed-lecture-summaries/invitations

**Comment by kblavvv** [comment]
Assalaam alaikum warahmatullahi wabarakatuhu. Sorry I had started to summarize but I wanted to publish it together. I had some family problems come up so found it difficult to sit near comp ans do it. Please keep me assigned Insha Allāh if it doesn't trouble you as I really do wanna contribute bi-idhnillah.

**Comment by ikhbatalqulub** [comment]
@kblavvv 
wa alaykum alSalaam wa rahmatAllah wa barakatuhu. If you are a brother, can you message me on twitter (@abdallahghamidi) or facebook (@abdallah.ghamidi1)? There might be an opportunity for you to contribute. Otherwise, I will have to get back to you in a week in shaa Allah with a suggestion

**Comment by kblavvv** [comment]
Waiting for a suggestion Insha Allah

**Comment by ikhbatalqulub** [comment]
@kblavvv I'm sorry for that. I completely forgot. I've invited you as a collaborator and will assign you new tasks in shaa Allah. The task is slightly different so make sure to read the new instructions at the top of each issue
